vim.pack.add({
	"https://www.github.com/lewis6991/gitsigns.nvim",
	"https://www.github.com/echasnovski/mini.nvim",
	"https://www.github.com/ibhagwan/fzf-lua",
	"https://github.com/stevearc/oil.nvim",
	"https://github.com/jakemason/ouroboros.nvim",
	"https://github.com/uga-rosa/ccc.nvim",
	"https://github.com/nvim-lua/plenary.nvim.git",
	"https://github.com/nvzone/volt",
	"https://github.com/nvim-tree/nvim-web-devicons",
	"https://github.com/nvim-lualine/lualine.nvim",
	"https://github.com/obsidian-nvim/obsidian.nvim",
	"https://github.com/jake-stewart/multicursor.nvim",
	"https://github.com/hrsh7th/nvim-cmp",
	"https://github.com/rafamadriz/friendly-snippets",
	"https://github.com/hrsh7th/cmp-nvim-lsp",
	"https://github.com/hrsh7th/cmp-buffer",
	"https://github.com/hrsh7th/cmp-path",
	"https://github.com/hrsh7th/cmp-nvim-lsp-signature-help",
	"https://github.com/onsails/lspkind.nvim",
	"https://github.com/saadparwaiz1/cmp_luasnip",
	"https://github.com/meanderingprogrammer/render-markdown.nvim",
	-- Language Server Protocols
	"https://www.github.com/neovim/nvim-lspconfig",
	"https://github.com/mason-org/mason.nvim",
	"https://github.com/mason-org/mason-lspconfig.nvim",
	"https://github.com/creativenull/efmls-configs-nvim",
	"https://github.com/ManuLinares/nvim-c3",
	"https://github.com/nvim-treesitter/nvim-treesitter-context",
	{
		src = "https://github.com/nvim-treesitter/nvim-treesitter",
		branch = "main",
		build = ":TSUpdate",
	},
	{
		src = "https://github.com/nvzone/floaterm",
		cmd = "FloatermToggle",
	},
	{
		src = "https://github.com/folke/flash.nvim",
		event = "VeryLazy",
	},
	{
		src = "https://github.com/folke/which-key.nvim",
		event = "VeryLazy",
		opts = {},
	},
	{
		src = "https://github.com/christoomey/vim-tmux-navigator",
		cmd = {
			"TmuxNavigateLeft",
			"TmuxNavigateDown",
			"TmuxNavigateUp",
			"TmuxNavigateRight",
			"TmuxNavigatePrevious",
			"TmuxNavigatorProcessList",
		},
		keys = {
			{ "<c-h>", "<cmd><C-U>TmuxNavigateLeft<cr>" },
			{ "<c-j>", "<cmd><C-U>TmuxNavigateDown<cr>" },
			{ "<c-k>", "<cmd><C-U>TmuxNavigateUp<cr>" },
			{ "<c-l>", "<cmd><C-U>TmuxNavigateRight<cr>" },
			{ "<c-\\>", "<cmd><C-U>TmuxNavigatePrevious<cr>" },
		},
	},
	{
		src = "https://github.com/eldritch-theme/eldritch.nvim",
		lazy = false,
		priotity = 1000,
	},
	{
		src = "https://github.com/maxmx03/fluoromachine.nvim",
		lazy = false,
		priotity = 1000,
	},
	{
		src = "https://github.com/folke/snacks.nvim",
		priotity = 1000,
		lazy = false,
	},
	{
		src = "https://github.com/xiyaowong/nvim-transparent",
		lazy = false,
		priority = 1000,
	},
	{
		src = "https://github.com/L3MON4D3/LuaSnip",
		build = "make install_jsregexp",
	},
	{
		src = "https://github.com/nvimdev/lspsaga.nvim",
	},
})
